### CATEGORY ###
###

# @name get categories
GET {{host}}/{{apiPrefix}}/v1/categories
Accept: application/json
###

# @name get category by id
GET {{host}}/{{apiPrefix}}/v1/categories/6662bd0cc5b412be3ec843cb
Accept: application/json
###

# @name add category
POST {{host}}/{{apiPrefix}}/v1/categories
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Computers",
  "icon": "icon-computer",
  "color": "#444"
}
###

# @name update category by id
PUT {{host}}/{{apiPrefix}}/v1/categories/6662c04264c0588d23b7536c
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Wooden Hardware",
  "icon": "icon-computer",
  "color": "#555"
}
###

# @name delete category by id
DELETE {{host}}/{{apiPrefix}}/v1/categories/6662baba0fa17126e55ae8d2
Authorization: Bearer {{auth_token}}
###

### PRODUCT ###
###

# @name get products
GET {{host}}/{{apiPrefix}}/v1/products?categories=6662b82439fd3040bef8f7e0
Accept: application/json
###

# @name get featured products
GET {{host}}/{{apiPrefix}}/v1/products/featured/2
Accept: application/json
###

# @name get product by id
GET {{host}}/{{apiPrefix}}/v1/products/6662de275eefc5d955227f7e
Accept: application/json
###

# @name add product
POST {{host}}/{{apiPrefix}}/v1/products
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="Macbook PNG 982x905.png"
Content-Type: image/png

< /Users/jay/Downloads/Macbook PNG 982x905.png
--boundary123
Content-Disposition: form-data; name="name"

MacBook 2020 15"
--boundary123--
Content-Disposition: form-data; name="description"

Brand new Apple MacBook Pro 2020 with touch bar
--boundary123--
Content-Disposition: form-data; name="richDescription"

<b>Best In class, Great choice for gifts</b>
--boundary123--
Content-Disposition: form-data; name="brand"

Apple
--boundary123--
Content-Disposition: form-data; name="price"

150
--boundary123--
Content-Disposition: form-data; name="category"

6662b82439fd3040bef8f7e0
--boundary123--
Content-Disposition: form-data; name="countInStock"

100
--boundary123--
Content-Disposition: form-data; name="rating"

4
--boundary123--
Content-Disposition: form-data; name="numReviews"

0
--boundary123--
Content-Disposition: form-data; name="isFeatured"

false
--boundary123--

{
  "name": "MacBook 2020 15\"",
  "description": "Brand new Apple MacBook Pro 2020 with touch bar",
  "richDescription": "<b>Best In class, Great choice for gifts</b>",
  "image": "",
  "brand": "Apple",
  "price": 150,
  "category": "6662b82439fd3040bef8f7e0",
  "countInStock": 0,
  "rating": 4,
  "numReviews": 0,
  "isFeatured": false
}
###
# @name add gallery images to product
PUT {{host}}/{{apiPrefix}}/v1/products/gallery-images/6662b82439fd3040bef8f7e0
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="images"; filename="Macbook PNG 982x905.png"
Content-Type: image/png

< /Users/jay/Downloads/Macbook PNG 982x905.png
--boundary123--
###

# @name update product by id
PUT {{host}}/{{apiPrefix}}/v1/products/6662deba29b147baa88af909
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "MacBook 2020 17\"",
  "description": "Brand new Apple MacBook Pro 2020 with touch bar",
  "richDescription": "<b>Best In class, Great choice for productivity</b>",
  "image": "",
  "brand": "Apple",
  "price": 150,
  "category": "6662b82439fd3040bef8f7e0",
  "countInStock": 0,
  "rating": 4,
  "numReviews": 0,
  "isFeatured": true
}
###

# @name delete product by id
DELETE {{host}}/{{apiPrefix}}/v1/products/6662de275eefc5d955227f7e
Authorization: Bearer {{auth_token}}
###

# @name get products count
GET {{host}}/{{apiPrefix}}/v1/products/count
Authorization: Bearer {{auth_token}}
###

### USER ###
###

# @name get users
GET {{host}}/{{apiPrefix}}/v1/users
Accept: application/json
Authorization: Bearer {{auth_token}}
###

# @name login user
POST {{host}}/{{apiPrefix}}/v1/users/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "Password@1"
}
> {% client.global.set("auth_token", response.body.token); %}
###

# @name get users by id
GET {{host}}/{{apiPrefix}}/v1/users/6663ea3bf4bacd90033e21cf
Accept: application/json
Authorization: Bearer {{auth_token}}
###

# @name register user
POST {{host}}/{{apiPrefix}}/v1/users/register
Content-Type: application/json

{
  "name": "Jay Tailor",
  "email": "admin@gmail.com",
  "password": "Password@1",
  "street": "Smarat Street",
  "apartment": "",
  "city": "Surat",
  "zip": "123123",
  "country": "India",
  "phone": "9192939495",
  "isAdmin": false
}
###

# @name update users by id
PUT {{host}}/{{apiPrefix}}/v1/users/6663ea3bf4bacd90033e21cf
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Jay Tailor 45",
  "street": "Smarat Street 1",
  "apartment": "",
  "city": "Surat",
  "zip": "321321",
  "country": "India",
  "phone": "9999939495"
}
###

# @name delete user by id
DELETE {{host}}/{{apiPrefix}}/v1/users/6663ea3bf4bacd90033e21cf
Authorization: Bearer {{auth_token}}
###

# @name get users count
GET {{host}}/{{apiPrefix}}/v1/users/count
Authorization: Bearer {{auth_token}}
###

### Order ###
###

# @name get orders
GET {{host}}/{{apiPrefix}}/v1/orders
Accept: application/json
Authorization: Bearer {{auth_token}}
###

# @name get order
GET {{host}}/{{apiPrefix}}/v1/orders/666429b83845ec28bb7b400f
Accept: application/json
Authorization: Bearer {{auth_token}}
###

# @name create order
POST {{host}}/{{apiPrefix}}/v1/orders
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "orderItems": [
    {
      "quantity": 5,
      "product": "66640f82d60952b5be2c39cd"
    },
    {
      "quantity": 2,
      "product": "6662deba29b147baa88af909"
    }
  ],
  "shippingAddress1": "Shipping Address 1",
  "shippingAddress2": "Shipping Address 2",
  "city": "My City",
  "zip": "123123",
  "country": "India",
  "phone": "9988997766",
  "status": "Pending",
  "totalPrice": 100,
  "user": "6663e7d510690eadb280dd19"
}
###

# @name update order status
PUT {{host}}/{{apiPrefix}}/v1/orders/666429b83845ec28bb7b400f
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "status": "Shipped"
}
###

# @name delete order by id
DELETE {{host}}/{{apiPrefix}}/v1/orders/666429b83845ec28bb7b400f
Authorization: Bearer {{auth_token}}
###

# @name get total sales
GET {{host}}/{{apiPrefix}}/v1/orders/total-sales
Authorization: Bearer {{auth_token}}
###

# @name get order count
GET {{host}}/{{apiPrefix}}/v1/orders/count
Authorization: Bearer {{auth_token}}
###

# @name get user order
GET {{host}}/{{apiPrefix}}/v1/orders/user/6663e7d510690eadb280dd19
Authorization: Bearer {{auth_token}}
###